### ISSUE TITLE
30 hz reported

### ISSUE THREAD

**Issue by albmm74** [D0023R/linux_kernel_15khz#10]
Hello, I have been using these patches for several years to compile my kernels. They work great (excellent work, I am very grateful).

I've only been having one problem with all of them, what is that in 640x480i mode, both the desktop and certain applications recognize 30 hz refresh rate, which makes some emulators like Flycast not work properly:

https://github.com/flyinghead/flycast/discussions/1514

![imagen](https://github.com/user-attachments/assets/0b405b8c-c5e5-4aae-819d-7de1399fe87c)

I wanted to ask if there is a solution to this.

Thank you very much.

**Comment by D0023R** [comment]
Hi albmm74,

Thanks for your words, much appreciated :)

Can you please provide the output of the 'xrandr --verbose' command ?
Assuming the 02_linux_15khz_interlaced_mode_fix patch is applied. I suspect the 30kHz refresh rate is the result of the interlaced flag not being considered by the app into the screen total vertical refresh calculation. Instead, the refresh rate is reported as half of the rate for each odd and even frames.

**Comment by albmm74** [comment]
Thanks. All patches are applied. Now I'm using kernel 6.1.73 xanmod.

xrandr log attached. Many thanks.

[xrandr.txt](https://github.com/user-attachments/files/16360911/xrandr.txt)

**Comment by D0023R** [comment]
On the last lines, you can see that the resolution is correctly set (640x480 interlaced 15.75kHz and 60Hz vertical refresh).
Thus, the issue is outside the kernel. 
I do not know how the application (or back end) is handling the refresh/vblank calculation. If you are seeing a speed inconsistency, you can try to compile a kernel without the 02 patch-set and check if it fixes your issue (this will influence drmVBlank behaviour, not ideal but might bring a simple solution). Otherwise, the application will need to take into account the full frame refresh rate (60Hz) by checking the interlaced flag presence.

**Comment by albmm74** [comment]
Thanks again friend.

**Comment by D0023R** [comment]
Closed

**Comment by D0023R** [comment]
Close

**Comment by D0023R** [comment]
Closed
